apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: aspnet3core
spec:
  ports:
  - port: 8889
    protocol: TCP
    targetPort: 80
  selector:
    app: aspnet3core
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
  labels:
    app: aspnet3core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnet3core
  template:
    metadata:
      labels:
        app: aspnet3core
        environment: development
    spec:
      containers:
        - name: aspnet3-orders
          image: deathstroke45/petshoporders:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: apphost
              value: k8s
            - name: appenvironment
              value: development
