apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: aspnet3core
spec:
  ports:
  - port: 8889
    protocol: TCP
    targetPort: 80
  selector:
    app: aspnet3core
  type: NodePort
